### PR TITLE
Fix LATEST_VERSION_RANGE so it actually resolves the latest version

### PR DESCRIPTION
**Pull request by werthen**
I'm not very experienced in this testing suite, but I've seen that version ranges in general do work, except the `LATEST_VERSION_RANGE` never really gets tested. This range is faulty, as confirmed by the official maven documentation (http://maven.apache.org/enforcer/enforcer-rules/versionRanges.html) and own experience.

Now the range is set to `x >= 0.0`, instead of a range that doesn't make sense in the first place.

### CODE REVIEW

**Comment by splatch** [comment]
This area is indeed unclear as pax-url-mvn is running under osgi which have slightly different logic in handling versions especially on lower and upper bounds. For example maven excludes 4-snapshot and includes 5-SNAPSHOT in [4,5) range while osgi accepts first and excludes second treating snapshot as just qualifier.

**Comment by werthen** [comment]
I'm not a frequent OSGi developer, but wanting to test some stuff out in karaf, I noticed I could not pull a 0.0.x package without this patch applied.

**Comment by ANierbeck** [comment]
maybe @grgrzybek could take a look at this? 
He's been working on quite some improvements on the maven handling lately.
@werthen please also open an issue for this at our jira.

**Comment by grgrzybek** [comment]
I'm not fond of version ranges (we spent many man hours fixing problems related to version ranges), but this PR looks fine.

**Pull request merged**
