### PR TITLE
[PAXURL-326] Removed unneeded shaded dependencies: 5% size reduction.

### PR DESCRIPTION
**Pull request by CodingFabian**
Remove also the nekohtml exclusion because it is superfluous.

### CODE REVIEW

**Comment by CodingFabian** [comment]
as in #18 I removed the shading process. the shorter directories alone had a minimal effect on jar size, but I consider consistency with the other projects and especially debuggability (which is increased when my IDE can find the class because it is no longer shaded) as the major driver.

**Comment by bastijns-jeroen** [comment]
Hi @CodingFabian, the shading process wasn't initially there in assembly I just initially added it in the first commit of #18 and then again removed it because it was unnecessary. The driving factor to use shading in url-aether was to avoid conflicts with versions of maven and aether when using url-aether in a non-osgi context. See https://ops4j1.jira.com/browse/PAXURL-251.

@ANierbeck what is your opinion?

**Comment by ANierbeck** [comment]
The aether bundle is a special one, as it can be used outside the OSGi context, the shaded one is needed afaik, to make sure maven and aether don't get into a conflict. 
But @hwellmann knows best, he implemented it for a reason :-)

**Comment by grgrzybek** [comment]
I've reviewed the shade configuration for pax-url-aether with #417 here: 52dc4fa5179d71171a9d7dc7245a2bc894a573f8

**Pull request closed without merging**
